version: "3"
services:
  mysql-master:
    image: mysql:8.0
    container_name: proxysql-mysql-replication-master
    environment:
      MYSQL_ROOT_PASSWORD: 0003b166e5
      MYSQL_DATABASE: tinydb
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
      - ./master/data:/var/lib/mysql
      - ./master/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
  proxysql:
    image: proxysql/proxysql:2.0.12
    restart: always
    container_name: proxysql
    volumes: 
    - ./proxysql.cnf:/etc/proxysql.cnf
    - ./proxysql:/var/lib/proxysql
    ports:
    - "6033:6033"
    - "6032:6032"
    - "6080:6080"
